name: Deploy Infra and Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Build  image
        run: ./gradlew build -x test

      - name: Deploy Lambda
        env:
          CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
          DEFAULT_PASS: ${{ secrets.DEFAULT_PASS }}
        run: |
          echo "Deploying Lambda..."
          
          echo "Updating Lambda enviroment variables"
          aws lambda update-function-configuration \
            --function-name cpf-auth-lambda \
            --environment "Variables={CLIENT_ID=$CLIENT_ID,DEFAULT_PASS=$DEFAULT_PASS}"

          echo "Update Lambda code"
          aws lambda update-function-code \
            --function-name cpf-auth-lambda \
            --zip-file fileb://build/libs/fiap-tech-challenge-lambda-0.0.1-SNAPSHOT.jar

