name: Deploy Infra and Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Deploy Lambda
        env:
          USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          USER_POOL_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
          COGNITO_DUMMY_PASSWORD: ${{ secrets.DEFAULT_PASS }}
        run: |
          echo "Deploying Lambda..."
          aws lambda update-function-configuration \
            --function-name cpf-auth-lambda \
            --environment "Variables={USER_POOL_ID=$USER_POOL_ID,USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID,COGNITO_DUMMY_PASSWORD=$COGNITO_DUMMY_PASSWORD}"
